apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neon.fullname" . }}-s3
  labels:
    {{- include "neon.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretKey | quote }}
